# Sivan Toledo, 2008
# local makefile with frequently-changing values.

# Change the path to where you installed WinArm
#GCCBIN = c:/Programs/WinARM/bin/
#LPCBIN = c:/Programs/WinARM/bin/

GCCBIN = c:/utils/WinARM/bin/
LPCBIN = c:/utils/WinARM/bin/
GCCBIN =
LPCBIN =

# change the port number to that of the USB Serial Port
# (check under device manager in Windows)
#LPC21ISP_PORT = COM9
LPC21ISP_PORT = /dev/ttyUSB0

TARGET = main

LDSCRIPT = lpc2148-ram
LDSCRIPT = lpc2148-flash

