# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'devcfg.ui'
#
# Created: Wed Jul 27 01:50:31 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_devcfg(object):
    def setupUi(self, devcfg):
        devcfg.setObjectName(_fromUtf8("devcfg"))
        devcfg.resize(522, 648)
        self.verticalLayout = QtGui.QVBoxLayout(devcfg)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(devcfg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.vpnhostEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vpnhostEdit.sizePolicy().hasHeightForWidth())
        self.vpnhostEdit.setSizePolicy(sizePolicy)
        self.vpnhostEdit.setObjectName(_fromUtf8("vpnhostEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.vpnhostEdit)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.vpnportEdit = QtGui.QLineEdit(self.groupBox)
        self.vpnportEdit.setObjectName(_fromUtf8("vpnportEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.vpnportEdit)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.vpnmacEdit = QtGui.QLineEdit(self.groupBox)
        self.vpnmacEdit.setObjectName(_fromUtf8("vpnmacEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.vpnmacEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(devcfg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dhcpEdit = QtGui.QRadioButton(self.groupBox_2)
        self.dhcpEdit.setAutoExclusive(True)
        self.dhcpEdit.setObjectName(_fromUtf8("dhcpEdit"))
        self.gridLayout.addWidget(self.dhcpEdit, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(306, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.staticEdit = QtGui.QRadioButton(self.groupBox_2)
        self.staticEdit.setObjectName(_fromUtf8("staticEdit"))
        self.gridLayout.addWidget(self.staticEdit, 1, 0, 1, 1)
        self.staticGroup = QtGui.QGroupBox(self.groupBox_2)
        self.staticGroup.setTitle(_fromUtf8(""))
        self.staticGroup.setCheckable(False)
        self.staticGroup.setObjectName(_fromUtf8("staticGroup"))
        self.formLayout_2 = QtGui.QFormLayout(self.staticGroup)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.staticGroup)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.staddrEdit = QtGui.QLineEdit(self.staticGroup)
        self.staddrEdit.setObjectName(_fromUtf8("staddrEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.staddrEdit)
        self.label_4 = QtGui.QLabel(self.staticGroup)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.stmaskEdit = QtGui.QLineEdit(self.staticGroup)
        self.stmaskEdit.setObjectName(_fromUtf8("stmaskEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.stmaskEdit)
        self.label_5 = QtGui.QLabel(self.staticGroup)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.stgwEdit = QtGui.QLineEdit(self.staticGroup)
        self.stgwEdit.setObjectName(_fromUtf8("stgwEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.stgwEdit)
        self.label_6 = QtGui.QLabel(self.staticGroup)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.stdnsEdit = QtGui.QLineEdit(self.staticGroup)
        self.stdnsEdit.setObjectName(_fromUtf8("stdnsEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.stdnsEdit)
        self.gridLayout.addWidget(self.staticGroup, 1, 1, 2, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.physmacEdit = QtGui.QLineEdit(self.groupBox_2)
        self.physmacEdit.setObjectName(_fromUtf8("physmacEdit"))
        self.gridLayout.addWidget(self.physmacEdit, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(devcfg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.servpubkeyEdit = QtGui.QTextEdit(self.groupBox_4)
        self.servpubkeyEdit.setObjectName(_fromUtf8("servpubkeyEdit"))
        self.gridLayout_2.addWidget(self.servpubkeyEdit, 0, 1, 1, 2)
        self.servpubkeyLoad = QtGui.QPushButton(self.groupBox_4)
        self.servpubkeyLoad.setObjectName(_fromUtf8("servpubkeyLoad"))
        self.gridLayout_2.addWidget(self.servpubkeyLoad, 0, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.clientpubkeyEdit = QtGui.QTextEdit(self.groupBox_4)
        self.clientpubkeyEdit.setObjectName(_fromUtf8("clientpubkeyEdit"))
        self.gridLayout_2.addWidget(self.clientpubkeyEdit, 1, 1, 1, 1)
        self.genpaitBtn = QtGui.QPushButton(self.groupBox_4)
        self.genpaitBtn.setObjectName(_fromUtf8("genpaitBtn"))
        self.gridLayout_2.addWidget(self.genpaitBtn, 1, 2, 2, 1)
        self.clientpubkeyLoad = QtGui.QPushButton(self.groupBox_4)
        self.clientpubkeyLoad.setObjectName(_fromUtf8("clientpubkeyLoad"))
        self.gridLayout_2.addWidget(self.clientpubkeyLoad, 1, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.clientprivkeyEdit = QtGui.QTextEdit(self.groupBox_4)
        self.clientprivkeyEdit.setObjectName(_fromUtf8("clientprivkeyEdit"))
        self.gridLayout_2.addWidget(self.clientprivkeyEdit, 2, 1, 1, 1)
        self.clientprivkeyLoad = QtGui.QPushButton(self.groupBox_4)
        self.clientprivkeyLoad.setObjectName(_fromUtf8("clientprivkeyLoad"))
        self.gridLayout_2.addWidget(self.clientprivkeyLoad, 2, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.buttonBox = QtGui.QDialogButtonBox(devcfg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(devcfg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), devcfg.reject)
        QtCore.QObject.connect(self.staticEdit, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.staticGroup.setEnabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), devcfg.accept)
        QtCore.QMetaObject.connectSlotsByName(devcfg)

    def retranslateUi(self, devcfg):
        devcfg.setWindowTitle(QtGui.QApplication.translate("devcfg", "Configure VPN device", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("devcfg", "VPN Server configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("devcfg", "Server host or IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("devcfg", "Server port:", None, QtGui.QApplication.UnicodeUTF8))
        self.vpnportEdit.setInputMask(QtGui.QApplication.translate("devcfg", "#####; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("devcfg", "VPN MAC:", None, QtGui.QApplication.UnicodeUTF8))
        self.vpnmacEdit.setInputMask(QtGui.QApplication.translate("devcfg", "HH:HH:HH:HH:HH:HH; ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("devcfg", "Guest network configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.dhcpEdit.setText(QtGui.QApplication.translate("devcfg", "Configure using DHCP", None, QtGui.QApplication.UnicodeUTF8))
        self.staticEdit.setText(QtGui.QApplication.translate("devcfg", "Static IP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("devcfg", "IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.staddrEdit.setInputMask(QtGui.QApplication.translate("devcfg", "###.###.###.###; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("devcfg", "Subnet mask:", None, QtGui.QApplication.UnicodeUTF8))
        self.stmaskEdit.setInputMask(QtGui.QApplication.translate("devcfg", "###.###.###.###; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("devcfg", "Gateway:", None, QtGui.QApplication.UnicodeUTF8))
        self.stgwEdit.setInputMask(QtGui.QApplication.translate("devcfg", "###.###.###.###; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("devcfg", "DNS:", None, QtGui.QApplication.UnicodeUTF8))
        self.stdnsEdit.setInputMask(QtGui.QApplication.translate("devcfg", "###.###.###.###; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("devcfg", "MAC on guest network:", None, QtGui.QApplication.UnicodeUTF8))
        self.physmacEdit.setInputMask(QtGui.QApplication.translate("devcfg", "HH:HH:HH:HH:HH:HH; ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("devcfg", "Key management", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("devcfg", "Server public key:", None, QtGui.QApplication.UnicodeUTF8))
        self.servpubkeyLoad.setText(QtGui.QApplication.translate("devcfg", "Load...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("devcfg", "Client public key:", None, QtGui.QApplication.UnicodeUTF8))
        self.genpaitBtn.setText(QtGui.QApplication.translate("devcfg", "&Generate\n"
"pair", None, QtGui.QApplication.UnicodeUTF8))
        self.clientpubkeyLoad.setText(QtGui.QApplication.translate("devcfg", "Load...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("devcfg", "Client private key:", None, QtGui.QApplication.UnicodeUTF8))
        self.clientprivkeyLoad.setText(QtGui.QApplication.translate("devcfg", "Load...", None, QtGui.QApplication.UnicodeUTF8))

