#!/bin/bash -e

# determine absolute path of the project
SCRIPT_DIR=$(dirname $(readlink -e $0))
PROJECT_ROOT=$(readlink -e $SCRIPT_DIR/..)

# check whether all needed components are compiled
if [ ! -e $PROJECT_ROOT/util/polarssl/libpolarssl.so ]; then
    echo "libpolarssl.so was not found. You must compile polarssl util library!"
    exit 1
fi

# set up environment variables
export LD_LIBRARY_PATH=$PROJECT_ROOT/util/polarssl:$LD_LIBRARY_PATH
export PYTHONPATH=$PROJECT_ROOT/util/polarssl:$PROJECT_ROOT/sw:$PYTHONPATH

# run the python server - it will exit upon reception of INT signal
python keygen.py $*
